<a href="https://colab.research.google.com/github/DaiyanNDahy/FlyRankInternML/blob/main/work/notebooks/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/DaiyanNDahy/FlyRankInternML/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

In [1]:
print("ML Task Type: Ranking confirmed.")

ML Task Type: Ranking confirmed.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

In [2]:
print("Target/Proxy: Relevance score or engagement probability confirmed.")

Target/Proxy: Relevance score or engagement probability confirmed.

## 3. Success metric

*One metric you can defend. What number means 'good'?*

In [3]:
print("Success Metric: Normalized Discounted Cumulative Gain (NDCG) @ k confirmed.")

Success Metric: Normalized Discounted Cumulative Gain (NDCG) @ k confirmed.

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [4]:
import pandas as pd
from datasets import load_dataset
import numpy as np

# Load the dataset
ds = load_dataset("FlyRank/internship-starter")

# Convert the 'train' split to a pandas DataFrame
df = ds['train'].to_pandas()

# Display the first 5 rows to show the unit of analysis
print("Unit of analysis (first 5 rows):")
display(df.head())

# Adding a placeholder for a 'relevance_score' column.
# In a real system, this would be calculated from user behavior (e.g., clicks, time spent).
# For this exercise, we'll create a synthetic one just to show its presence.
df['relevance_score'] = np.random.rand(len(df)) # Placeholder: random scores

print("\nDataFrame with a sketched 'relevance_score' column:")
display(df.head())

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/1.48k [00:00<?, ?B/s]

content_refresh_anonymized.csv:   0%|          | 0.00/8.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/30000 [00:00<?, ? examples/s]

Unit of analysis (first 5 rows):

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,trend_pct,health_score,needs_indexing,is_quick_win,needs_ctr_fix,needs_engagement_fix,ai_opportunity,is_underperformer,is_declining,is_initial_refresh_candidate
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,-41.4,50,False,False,False,False,False,False,True,True
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,-57.7,40,False,True,False,False,False,False,True,True
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,-60.9,40,False,False,False,False,False,False,True,False
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,-13.8,60,False,False,False,True,False,False,False,True
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,-34.7,40,False,False,False,True,True,False,True,False

DataFrame with a sketched 'relevance_score' column:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,health_score,needs_indexing,is_quick_win,needs_ctr_fix,needs_engagement_fix,ai_opportunity,is_underperformer,is_declining,is_initial_refresh_candidate,relevance_score
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,50,False,False,False,False,False,False,True,True,0.340697
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,40,False,True,False,False,False,False,True,True,0.567013
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,40,False,False,False,False,False,False,True,False,0.424735
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,60,False,False,False,True,False,False,False,True,0.059446
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,40,False,False,False,True,True,False,True,False,0.748279

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

In [5]:
print("Why ML beats fixed rule: Complexity, personalization, and dynamic nature of data confirmed.")

Why ML beats fixed rule: Complexity, personalization, and dynamic nature of data confirmed.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.